-- CreateEnum
CREATE TYPE "LeaveDurationType" AS ENUM ('FULL_DAY', 'HALF_DAY');

-- AlterTable
ALTER TABLE "LeaveBalance" ALTER COLUMN "allocatedDays" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "usedDays" SET DEFAULT 0,
ALTER COLUMN "usedDays" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "remainingDays" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "LeaveRequest" ADD COLUMN     "durationType" "LeaveDurationType" NOT NULL DEFAULT 'FULL_DAY',
ALTER COLUMN "totalDays" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "paidDays" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "unpaidDays" SET DEFAULT 0,
ALTER COLUMN "unpaidDays" SET DATA TYPE DOUBLE PRECISION;
