import { prisma } from "../../config/prisma.js";
import { oauth2Client, GOOGLE_SCOPES } from "../../config/google.js";
import { AppError } from "../../utils/api.js";
import { startOfDay } from "../../utils/dates.js";
import { google } from "googleapis";
import { env } from "../../config/env.js";

/**
 * Generates the Google Authorization URL for user consent
 */
export function getGoogleAuthUrl() {
  console.log("Generating Google Auth URL with Redirect URI:", env.GOOGLE_REDIRECT_URL);
  return oauth2Client.generateAuthUrl({
    access_type: "offline", // Required to get Refresh Token
    scope: GOOGLE_SCOPES,
    include_granted_scopes: true,
    prompt: "consent", // Ensure we get the refresh token every time they link
  });
}

/**
 * Exchanges auth code for tokens and links user profile
 */
export async function linkGoogleAccount(userId: number, code: string) {
  const { tokens } = await oauth2Client.getToken(code);
  
  if (!tokens.refresh_token) {
    // If user already linked, Google might not send refresh token unless prompt=consent is used
    // or if we already have it.
    throw new AppError("Failed to obtain refresh token. Please un-link and re-link your account.", 400);
  }

  oauth2Client.setCredentials(tokens);

  const oauth2 = google.oauth2({ version: "v2", auth: oauth2Client });
  const userInfo = await oauth2.userinfo.get();

  if (!userInfo.data.id) {
    throw new AppError("Failed to fetch Google user profile.", 500);
  }

  // Update user in DB
  const updatedUser = await prisma.user.update({
    where: { id: userId },
    data: {
      googleId: userInfo.data.id,
      googleRefreshToken: tokens.refresh_token,
      isGoogleLinked: true,
    },
  });

  return {
    email: userInfo.data.email,
    isLinked: updatedUser.isGoogleLinked,
  };
}

/**
 * Unlinks Google account from user
 */
export async function unlinkGoogleAccount(userId: number) {
  await prisma.user.update({
    where: { id: userId },
    data: {
      googleId: null,
      googleRefreshToken: null,
      isGoogleLinked: false,
    },
  });

  return { isLinked: false };
}

/**
 * Creates a Google Meet link by creating a temporary calendar event
 */
export async function createMeetLink(userId: number, summary: string = "HRMS Instant Meeting") {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { googleRefreshToken: true },
  });

  if (!user?.googleRefreshToken) {
    throw new AppError("Google account not linked.", 403);
  }

  oauth2Client.setCredentials({
    refresh_token: user.googleRefreshToken,
  });

  const calendar = google.calendar({ version: "v3", auth: oauth2Client });

  const event = await calendar.events.insert({
    calendarId: "primary",
    conferenceDataVersion: 1,
    requestBody: {
      summary,
      description: "Generated by HRMS Command Center",
      start: { dateTime: new Date().toISOString() },
      end: { dateTime: new Date(Date.now() + 3600000).toISOString() }, // 1 hour later
      conferenceData: {
        createRequest: {
          requestId: `hrms-meet-${Date.now()}`,
          conferenceSolutionKey: { type: "hangoutsMeet" },
        },
      },
    },
  });

  const meetLink = event.data.hangoutLink;

  if (!meetLink) {
    throw new AppError("Failed to generate Google Meet link.", 500);
  }

  return { meetLink };
}

/**
 * Syncs an approved leave request to the employee's Google Calendar as an OOO event
 */
export async function syncLeaveToGoogleCalendar(params: {
  employeeId: number;
  startDate: Date;
  endDate: Date;
  leaveTypeName: string;
  reason: string;
}) {
  const user = await prisma.user.findFirst({
    where: { employee: { id: params.employeeId } },
    select: { googleRefreshToken: true },
  });

  if (!user?.googleRefreshToken) {
    // Silently return if not linked, or we could log it.
    // For now, we don't want to block the leave approval process if Google is not linked.
    return { synced: false, reason: "Google account not linked" };
  }

  oauth2Client.setCredentials({
    refresh_token: user.googleRefreshToken,
  });

  const calendar = google.calendar({ version: "v3", auth: oauth2Client });

  try {
    await calendar.events.insert({
      calendarId: "primary",
      requestBody: {
        summary: `OOO: ${params.leaveTypeName}`,
        description: `Approved Leave from HRMS. Reason: ${params.reason}`,
        start: { date: params.startDate.toISOString().split("T")[0] },
        end: { date: new Date(params.endDate.getTime() + 86400000).toISOString().split("T")[0] }, // end date is exclusive in Google Calendar
        transparency: "opaque", // busy
        status: "confirmed",
      },
    });

    return { synced: true };
  } catch (error) {
    console.error("Failed to sync leave to Google Calendar:", error);
    return { synced: false, error };
  }
}

/**
 * Syncs all future holidays to the user's Google Calendar
 */
export async function syncHolidaysToGoogleCalendar(userId: number) {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { googleRefreshToken: true },
  });

  if (!user?.googleRefreshToken) {
    throw new AppError("Google account not linked.", 403);
  }

  const futureExceptions = await prisma.calendarException.findMany({
    where: {
      date: { gte: startOfDay(new Date()) },
    },
    orderBy: { date: "asc" },
  });

  if (futureExceptions.length === 0) {
    return { syncedCount: 0, message: "No upcoming schedule exceptions to sync." };
  }

  oauth2Client.setCredentials({
    refresh_token: user.googleRefreshToken,
  });

  const calendar = google.calendar({ version: "v3", auth: oauth2Client });
  
  // Get existing events to avoid duplicates
  const existingEvents = await calendar.events.list({
    calendarId: "primary",
    timeMin: startOfDay(new Date()).toISOString(),
    singleEvents: true,
  });

  let syncedCount = 0;

  for (const exc of futureExceptions) {
    const summary = exc.type === "WORKING_SATURDAY" 
      ? `💻 Working Saturday: ${exc.name || "Shift"}` 
      : `🌴 Holiday: ${exc.name || "Public Holiday"}`;
    
    // Simple deduplication check
    const isDuplicate = existingEvents.data.items?.some(
      event => event.summary === summary && event.start?.date === exc.date.toISOString().split("T")[0]
    );

    if (isDuplicate) continue;

    try {
      await calendar.events.insert({
        calendarId: "primary",
        requestBody: {
          summary,
          description: exc.description || "Synced from HRMS",
          start: { date: exc.date.toISOString().split("T")[0] },
          end: { date: new Date(exc.date.getTime() + 86400000).toISOString().split("T")[0] },
          transparency: exc.type === "WORKING_SATURDAY" ? "opaque" : "transparent",
          colorId: exc.type === "WORKING_SATURDAY" ? "10" : "5", // 10 is Basil (Green), 5 is Banana (Yellow)
          status: "confirmed",
        },
      });
      syncedCount++;
    } catch (err) {
      console.error(`Failed to sync exception ${exc.name}:`, err);
    }
  }

  return { syncedCount };
}

/**
 * Sends a notification to a Google Chat Space using either a Webhook or the Chat API
 */
export async function sendTeamNotification(text: string, userId?: number) {
  const webhookUrl = process.env.GOOGLE_CHAT_WEBHOOK_URL;
  const spaceName = process.env.GOOGLE_CHAT_SPACE_ID; // e.g., 'spaces/XXXXXXXX'

  // Prioritize Webhook if configured and direct
  if (webhookUrl && webhookUrl.startsWith("http")) {
    try {
      const response = await fetch(webhookUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json; charset=UTF-8" },
        body: JSON.stringify({ text }),
      });
      if (response.ok) return { sent: true, method: "webhook" };
    } catch (error) {
      console.error("Webhook notification failed:", error);
    }
  }

  // Fallback to Chat API if userId is provided
  if (userId && spaceName) {
    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: { googleRefreshToken: true },
    });

    if (user?.googleRefreshToken) {
      try {
        oauth2Client.setCredentials({ refresh_token: user.googleRefreshToken });
        const chat = google.chat({ version: "v1", auth: oauth2Client });
        await chat.spaces.messages.create({
          parent: spaceName,
          requestBody: { text },
        });
        return { sent: true, method: "api" };
      } catch (error) {
        console.error("Chat API notification failed:", error);
      }
    }
  }

  return { sent: false, reason: "No valid notification channel configured" };
}
